### ISSUE TITLE
Apply for priors box parameters of 'onnx' model

### ISSUE THREAD

**Issue by enemy1205** [ShiqiYu/libfacedetection.train#55]
In file `config/yufacedet.yaml`
```
  anchor:
    min_sizes: [[10, 16, 24], [32, 48], [64, 96], [128, 192, 256]]
    steps: [8, 16, 32, 64]
    ratio: [1.]
    clip: False
```
These parameters are based on the `weights/yunet_final.pth` model .
But when i use the model with a fixed input size `eg.onnx/yunet_yunet_final_320_320_simplify.onnx` , this set of parameters will not match.
I wish to get a set of parameters which is able to adapt to the `onnx` model.
Thanks
